apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- svc.yaml

patchesStrategicMerge:
- deployment.yaml
- svc.yaml
patches:
  - target:
      kind: Deployment
    path: patch.yaml
  - target:
      kind: Service
    path: patch.yaml
