apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: placeholder
  template:
    metadata:
      labels:
        app: placeholder
    spec:
      containers:
      - name: placeholder
        image: placeholder
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
